"""ADD: new column and table

Revision ID: 3b169d89cc0e
Revises: ccc28eb63ca1
Create Date: 2025-10-28 11:18:46.985471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b169d89cc0e'
down_revision: Union[str, Sequence[str], None] = 'ccc28eb63ca1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'products',
        sa.Column('rating', sa.Float(), nullable=False, server_default=sa.text('0.0'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'rating')
    # ### end Alembic commands ###
